In [5]:
import pandas as pd
import os

RAW_PATH = "../data/raw"

dim_file = os.path.join(RAW_PATH, "DimTables.xlsx")
internet_file = os.path.join(RAW_PATH, "FactInternetSales.xlsx")
reseller_file = os.path.join(RAW_PATH, "FactResellerSales.xlsx")

print("Checking raw dataset files...\n")

for file in [dim_file, internet_file, reseller_file]:
    print(f"{os.path.basename(file)} : {'Found' if os.path.exists(file) else 'NOT FOUND'}")

Checking raw dataset files...

DimTables.xlsx : Found
FactInternetSales.xlsx : Found
FactResellerSales.xlsx : Found

In [6]:
dim_excel = pd.ExcelFile(dim_file)

print("Dimension table sheets:")
for sheet in dim_excel.sheet_names:
    print(" -", sheet)

fact_internet = pd.read_excel(internet_file)
fact_reseller = pd.read_excel(reseller_file)

print("\nFact Internet Sales shape:", fact_internet.shape)
print("Fact Reseller Sales shape:", fact_reseller.shape)

Dimension table sheets:
 - DimCustomer
 - DimEmployee
 - DimGeography
 - DimProduct
 - DimReseller
 - DimSalesTerritory

Fact Internet Sales shape: (60398, 13)
Fact Reseller Sales shape: (60899, 14)

In [7]:

dim_customer = pd.read_excel(dim_file, sheet_name="DimCustomer")
dim_employee = pd.read_excel(dim_file, sheet_name="DimEmployee")
dim_geography = pd.read_excel(dim_file, sheet_name="DimGeography")
dim_product = pd.read_excel(dim_file, sheet_name="DimProduct")
dim_reseller = pd.read_excel(dim_file, sheet_name="DimReseller")
dim_sales_territory = pd.read_excel(dim_file, sheet_name="DimSalesTerritory")

print("Dimension table shapes:\n")

print("DimCustomer:", dim_customer.shape)
print("DimEmployee:", dim_employee.shape)
print("DimGeography:", dim_geography.shape)
print("DimProduct:", dim_product.shape)
print("DimReseller:", dim_reseller.shape)
print("DimSalesTerritory:", dim_sales_territory.shape)

Dimension table shapes:

DimCustomer: (18484, 13)
DimEmployee: (21, 9)
DimGeography: (655, 6)
DimProduct: (397, 7)
DimReseller: (701, 4)
DimSalesTerritory: (11, 4)

In [8]:

datasets = {
    "DimCustomer": dim_customer,
    "DimEmployee": dim_employee,
    "DimGeography": dim_geography,
    "DimProduct": dim_product,
    "DimReseller": dim_reseller,
    "DimSalesTerritory": dim_sales_territory,
    "FactInternetSales": fact_internet,
    "FactResellerSales": fact_reseller
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * len(name))
    print(df.dtypes)

DimCustomer
-----------
CustomerKey                   int64
GeographyKey                  int64
CustomerName                    str
BirthDate            datetime64[us]
MaritalStatus                   str
Gender                          str
EmailAddress                    str
YearlyIncome                  int64
Education                       str
Occupation                      str
HouseOwnerFlag                int64
Address                         str
FirstPurchaseDate    datetime64[us]
dtype: object

DimEmployee
-----------
EmployeeKey                   int64
ParentEmployeeKey           float64
SalesTerritoryKey             int64
EmployeeName                    str
Title                           str
EmailAddress                    str
DepartmentName                  str
HireDate             datetime64[us]
BirthDate            datetime64[us]
dtype: object

DimGeography
------------
GeographyKey         int64
City                   str
State                  str
Country                str
PostalCode             str
SalesTerritoryKey    int64
dtype: object

DimProduct
----------
ProductKey               int64
ProductSubcategoryKey    int64
Product                    str
Color                      str
Model                      str
Subcategory                str
Category                   str
dtype: object

DimReseller
-----------
ResellerKey     int64
GeographyKey    int64
BusinessType      str
ResellerName      str
dtype: object

DimSalesTerritory
-----------------
SalesTerritoryKey        int64
SalesTerritoryRegion       str
SalesTerritoryCountry      str
SalesTerritoryGroup        str
dtype: object

FactInternetSales
-----------------
ProductKey                 int64
CustomerKey                int64
SalesTerritoryKey          int64
SalesOrderNumber             str
SalesOrderLineNumber       int64
DiscountAmount             int64
TotalProductCost         float64
SalesAmount              float64
Freight                  float64
CarrierTrackingNumber    float64
OrderDate                    str
DueDate                      str
ShipDate                     str
dtype: object

FactResellerSales
-----------------
ProductKey               float64
ResellerKey              float64
EmployeeKey              float64
SalesTerritoryKey        float64
SalesOrderNumber             str
SalesOrderLineNumber     float64
DiscountAmount           float64
TotalProductCost         float64
SalesAmount              float64
Freight                  float64
CarrierTrackingNumber        str
OrderDate                    str
DueDate                      str
ShipDate                     str
dtype: object

In [9]:

for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * len(name))
    print(df.isnull().sum())

DimCustomer
-----------
CustomerKey          0
GeographyKey         0
CustomerName         0
BirthDate            0
MaritalStatus        0
Gender               0
EmailAddress         0
YearlyIncome         0
Education            0
Occupation           0
HouseOwnerFlag       0
Address              0
FirstPurchaseDate    0
dtype: int64

DimEmployee
-----------
EmployeeKey          0
ParentEmployeeKey    1
SalesTerritoryKey    0
EmployeeName         0
Title                0
EmailAddress         0
DepartmentName       0
HireDate             0
BirthDate            0
dtype: int64

DimGeography
------------
GeographyKey         0
City                 0
State                0
Country              0
PostalCode           0
SalesTerritoryKey    0
dtype: int64

DimProduct
----------
ProductKey                0
ProductSubcategoryKey     0
Product                   0
Color                    56
Model                     0
Subcategory               0
Category                  0
dtype: int64

DimReseller
-----------
ResellerKey     0
GeographyKey    0
BusinessType    0
ResellerName    0
dtype: int64

DimSalesTerritory
-----------------
SalesTerritoryKey        0
SalesTerritoryRegion     1
SalesTerritoryCountry    1
SalesTerritoryGroup      1
dtype: int64

FactInternetSales
-----------------
ProductKey                   0
CustomerKey                  0
SalesTerritoryKey            0
SalesOrderNumber             0
SalesOrderLineNumber         0
DiscountAmount               0
TotalProductCost             0
SalesAmount                  0
Freight                      0
CarrierTrackingNumber    60398
OrderDate                    0
DueDate                      0
ShipDate                     0
dtype: int64

FactResellerSales
-----------------
ProductKey               44
ResellerKey              44
EmployeeKey              44
SalesTerritoryKey        44
SalesOrderNumber         44
SalesOrderLineNumber     44
DiscountAmount           44
TotalProductCost          3
SalesAmount               3
Freight                  44
CarrierTrackingNumber    44
OrderDate                44
DueDate                  44
ShipDate                 44
dtype: int64

In [10]:

for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()
    print(f"{name}: {duplicate_count} duplicate rows")

DimCustomer: 0 duplicate rows
DimEmployee: 0 duplicate rows
DimGeography: 0 duplicate rows
DimProduct: 0 duplicate rows
DimReseller: 0 duplicate rows
DimSalesTerritory: 0 duplicate rows
FactInternetSales: 0 duplicate rows
FactResellerSales: 2 duplicate rows

In [11]:

key_columns = {
    "DimCustomer": "CustomerKey",
    "DimEmployee": "EmployeeKey",
    "DimGeography": "GeographyKey",
    "DimProduct": "ProductKey",
    "DimReseller": "ResellerKey",
    "DimSalesTerritory": "SalesTerritoryKey"
}

for name, key in key_columns.items():
    df = datasets[name]
    duplicate_count = df[key].duplicated().sum()
    print(f"{name} - {key}: {duplicate_count} duplicate values")

DimCustomer - CustomerKey: 0 duplicate values
DimEmployee - EmployeeKey: 0 duplicate values
DimGeography - GeographyKey: 0 duplicate values
DimProduct - ProductKey: 0 duplicate values
DimReseller - ResellerKey: 0 duplicate values
DimSalesTerritory - SalesTerritoryKey: 0 duplicate values

In [12]:

fact_reseller[fact_reseller.duplicated(keep=False)]

,ProductKey,ResellerKey,EmployeeKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,DiscountAmount,TotalProductCost,SalesAmount,Freight,CarrierTrackingNumber,OrderDate,DueDate,ShipDate
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:

for name, df in datasets.items():
    blank_rows = df.isna().all(axis=1).sum()
    print(f"{name}: {blank_rows} completely blank rows")

DimCustomer: 0 completely blank rows
DimEmployee: 0 completely blank rows
DimGeography: 0 completely blank rows
DimProduct: 0 completely blank rows
DimReseller: 0 completely blank rows
DimSalesTerritory: 0 completely blank rows
FactInternetSales: 0 completely blank rows
FactResellerSales: 3 completely blank rows

In [15]:

for name, df in datasets.items():
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print(f"\n{name}")
    print("-" * len(name))

    if missing.empty:
        print("No missing values")
    else:
        print(missing)

DimCustomer
-----------
No missing values

DimEmployee
-----------
ParentEmployeeKey    1
dtype: int64

DimGeography
------------
No missing values

DimProduct
----------
Color    56
dtype: int64

DimReseller
-----------
No missing values

DimSalesTerritory
-----------------
SalesTerritoryRegion     1
SalesTerritoryCountry    1
SalesTerritoryGroup      1
dtype: int64

FactInternetSales
-----------------
CarrierTrackingNumber    60398
dtype: int64

FactResellerSales
-----------------
ProductKey               44
ResellerKey              44
EmployeeKey              44
SalesTerritoryKey        44
SalesOrderNumber         44
SalesOrderLineNumber     44
DiscountAmount           44
TotalProductCost          3
SalesAmount               3
Freight                  44
CarrierTrackingNumber    44
OrderDate                44
DueDate                  44
ShipDate                 44
dtype: int64

In [16]:

fact_reseller[fact_reseller.isna().any(axis=1)]

,ProductKey,ResellerKey,EmployeeKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,DiscountAmount,TotalProductCost,SalesAmount,Freight,CarrierTrackingNumber,OrderDate,DueDate,ShipDate
352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.722951e+05,4.893286e+05,NaN,NaN,NaN,NaN,NaN
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.469460e+06,1.538408e+06,NaN,NaN,NaN,NaN,NaN
1733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.108483e+06,1.165897e+06,NaN,NaN,NaN,NaN,NaN
2233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.171295e+05,8.447210e+05,NaN,NaN,NaN,NaN,NaN
3340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.236063e+06,2.324136e+06,NaN,NaN,NaN,NaN,NaN
4144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.633078e+06,1.702945e+06,NaN,NaN,NaN,NaN,NaN
4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.904294e+05,7.131167e+05,NaN,NaN,NaN,NaN,NaN
5389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.830481e+06,1.900789e+06,NaN,NaN,NaN,NaN,NaN
6043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.396767e+06,1.455280e+06,NaN,NaN,NaN,NaN,NaN
6538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.546459e+05,8.828999e+05,NaN,NaN,NaN,NaN,NaN
7651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.181837e+06,2.269117e+06,NaN,NaN,NaN,NaN,NaN
8471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.607008e+06,1.001804e+06,NaN,NaN,NaN,NaN,NaN
10195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338001e+06,2.393690e+06,NaN,NaN,NaN,NaN,NaN
10196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.468826e+06,3.601191e+06,NaN,NaN,NaN,NaN,NaN
15347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.735886e+06,2.885359e+06,NaN,NaN,NaN,NaN,NaN
16754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.724518e+06,1.802154e+06,NaN,NaN,NaN,NaN,NaN
19100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.919120e+06,3.053816e+06,NaN,NaN,NaN,NaN,NaN
20833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.073508e+06,2.185213e+06,NaN,NaN,NaN,NaN,NaN
21817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.267385e+06,1.317542e+06,NaN,NaN,NaN,NaN,NaN
23482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.308084e+06,2.384847e+06,NaN,NaN,NaN,NaN,NaN
24698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.497550e+06,1.563955e+06,NaN,NaN,NaN,NaN,NaN
26148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.782337e+06,1.865278e+06,NaN,NaN,NaN,NaN,NaN
28455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.765546e+06,2.880753e+06,NaN,NaN,NaN,NaN,NaN
30154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.887464e+06,1.987873e+06,NaN,NaN,NaN,NaN,NaN
32341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.847508e+06,2.665651e+06,NaN,NaN,NaN,NaN,NaN
32342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.463793e+06,4.212972e+06,NaN,NaN,NaN,NaN,NaN
39858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.325499e+06,4.047574e+06,NaN,NaN,NaN,NaN,NaN
41669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.285347e+06,2.282116e+06,NaN,NaN,NaN,NaN,NaN
44574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.460755e+06,3.483161e+06,NaN,NaN,NaN,NaN,NaN
47604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479960e+06,3.510949e+06,NaN,NaN,NaN,NaN,NaN
48987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.657962e+06,1.662547e+06,NaN,NaN,NaN,NaN,NaN
51064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.687670e+06,2.699301e+06,NaN,NaN,NaN,NaN,NaN
51066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.554948e+03,1.466010e+03,NaN,NaN,NaN,NaN,NaN
53243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.730455e+06,2.737188e+06,NaN,NaN,NaN,NaN,NaN
53248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.191829e+03,2.183376e+03,NaN,NaN,NaN,NaN,NaN
55042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.199567e+06,2.204542e+06,NaN,NaN,NaN,NaN,NaN
55045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.046738e+02,8.156400e+01,NaN,NaN,NaN,NaN,NaN
57891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.340792e+06,3.314519e+06,NaN,NaN,NaN,NaN,NaN
57894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.480582e+02,7.557840e+02,NaN,NaN,NaN,NaN,NaN
60897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.430306e+06,3.415479e+06,NaN,NaN,NaN,NaN,NaN
60898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.998011e+07,8.045060e+07,NaN,NaN,NaN,NaN,NaN

In [17]:

problem_rows = fact_reseller[fact_reseller.isna().any(axis=1)]

print("Total problematic rows:", len(problem_rows))
print("Completely blank rows:", problem_rows.isna().all(axis=1).sum())
print(
    "Rows with SalesAmount but no ProductKey:",
    problem_rows["SalesAmount"].notna().sum()
)
print(
    "Rows with TotalProductCost but no ProductKey:",
    problem_rows["TotalProductCost"].notna().sum()
)

Total problematic rows: 44
Completely blank rows: 3
Rows with SalesAmount but no ProductKey: 41
Rows with TotalProductCost but no ProductKey: 41

In [18]:

problem_rows = fact_reseller[fact_reseller["ProductKey"].isna()]

print("Problematic rows with sales values:")
print(
    problem_rows[
        ["TotalProductCost", "SalesAmount"]
    ].describe()
)

print("\nNormal transaction rows:")
print(
    fact_reseller[
        fact_reseller["ProductKey"].notna()
    ][["TotalProductCost", "SalesAmount"]].describe()
)

Problematic rows with sales values:
       TotalProductCost   SalesAmount
count      4.100000e+01  4.100000e+01
mean       3.901469e+06  3.924419e+06
std        1.223124e+07  1.230136e+07
min        1.046738e+02  8.156400e+01
25%        1.396767e+06  1.317542e+06
50%        2.073508e+06  2.185213e+06
75%        2.765546e+06  2.880753e+06
max        7.998011e+07  8.045060e+07

Normal transaction rows:
       TotalProductCost   SalesAmount
count      60855.000000  60855.000000
mean        1314.273509   1322.004716
std         2159.575059   2124.233758
min            0.856500      1.374000
25%           96.912200    127.800000
50%          461.444800    461.694000
75%         1510.301600   1466.010000
max        38530.385400  27893.619000

In [19]:

for name, df in {
    "FactInternetSales": fact_internet,
    "FactResellerSales": fact_reseller
}.items():
    
    print(f"\n{name}")
    print("-" * len(name))
    
    for column in ["OrderDate", "DueDate", "ShipDate"]:
        converted = pd.to_datetime(df[column], errors="coerce")
        invalid = converted.isna().sum()
        
        print(f"{column}: {invalid} invalid or missing dates")

FactInternetSales
-----------------
OrderDate: 0 invalid or missing dates
DueDate: 0 invalid or missing dates
ShipDate: 0 invalid or missing dates

FactResellerSales
-----------------
OrderDate: 44 invalid or missing dates
DueDate: 44 invalid or missing dates
ShipDate: 44 invalid or missing dates

In [20]:

for name, df in {
    "FactInternetSales": fact_internet,
    "FactResellerSales": fact_reseller
}.items():

    print(f"\n{name}")
    print("-" * len(name))

    for column in ["SalesAmount", "TotalProductCost", "DiscountAmount", "Freight"]:
        negative = (df[column] < 0).sum()
        zero = (df[column] == 0).sum()

        print(f"{column}: Negative = {negative}, Zero = {zero}")

FactInternetSales
-----------------
SalesAmount: Negative = 0, Zero = 0
TotalProductCost: Negative = 0, Zero = 0
DiscountAmount: Negative = 0, Zero = 60398
Freight: Negative = 0, Zero = 0

FactResellerSales
-----------------
SalesAmount: Negative = 0, Zero = 0
TotalProductCost: Negative = 0, Zero = 0
DiscountAmount: Negative = 0, Zero = 57573
Freight: Negative = 0, Zero = 0

In [21]:

checks = {
    "InternetSales - CustomerKey": (
        fact_internet["CustomerKey"],
        dim_customer["CustomerKey"]
    ),
    "InternetSales - ProductKey": (
        fact_internet["ProductKey"],
        dim_product["ProductKey"]
    ),
    "InternetSales - SalesTerritoryKey": (
        fact_internet["SalesTerritoryKey"],
        dim_sales_territory["SalesTerritoryKey"]
    ),
    "ResellerSales - ProductKey": (
        fact_reseller["ProductKey"],
        dim_product["ProductKey"]
    ),
    "ResellerSales - ResellerKey": (
        fact_reseller["ResellerKey"],
        dim_reseller["ResellerKey"]
    ),
    "ResellerSales - EmployeeKey": (
        fact_reseller["EmployeeKey"],
        dim_employee["EmployeeKey"]
    ),
    "ResellerSales - SalesTerritoryKey": (
        fact_reseller["SalesTerritoryKey"],
        dim_sales_territory["SalesTerritoryKey"]
    )
}

for name, (fact_key, dim_key) in checks.items():
    invalid = (~fact_key.isna()) & (~fact_key.isin(dim_key))
    print(f"{name}: {invalid.sum()} invalid references")

InternetSales - CustomerKey: 0 invalid references
InternetSales - ProductKey: 0 invalid references
InternetSales - SalesTerritoryKey: 0 invalid references
ResellerSales - ProductKey: 0 invalid references
ResellerSales - ResellerKey: 0 invalid references
ResellerSales - EmployeeKey: 0 invalid references
ResellerSales - SalesTerritoryKey: 0 invalid references

In [22]:

categorical_columns = {
    "DimCustomer": ["MaritalStatus", "Gender", "Education", "Occupation"],
    "DimProduct": ["Color", "Model", "Subcategory", "Category"],
    "DimReseller": ["BusinessType"],
    "DimSalesTerritory": ["SalesTerritoryRegion", "SalesTerritoryCountry", "SalesTerritoryGroup"]
}

for name, columns in categorical_columns.items():
    print(f"\n{name}")
    print("-" * len(name))

    df = datasets[name]

    for column in columns:
        print(f"\n{column}:")
        print(df[column].dropna().unique())

DimCustomer
-----------

MaritalStatus:
<StringArray>
['M', 'S']
Length: 2, dtype: str

Gender:
<StringArray>
['M', 'F']
Length: 2, dtype: str

Education:
<StringArray>
[          'Bachelors',     'Partial College',         'High School',
 'Partial High School',     'Graduate Degree']
Length: 5, dtype: str

Occupation:
<StringArray>
['Professional', 'Management', 'Skilled Manual', 'Clerical', 'Manual']
Length: 5, dtype: str

DimProduct
----------

Color:
<StringArray>
[       'Multi',        'Black',       'Yellow', 'Silver/Black',
       'Silver',          'Red',        'White',         'Blue',
         'Grey']
Length: 9, dtype: str

Model:
<StringArray>
['Long-Sleeve Logo Jersey',                 'LL Fork',
                 'ML Fork',                 'HL Fork',
  'LL Mountain Handlebars', 'LL Mountain Front Wheel',
 'ML Mountain Front Wheel', 'HL Mountain Front Wheel',
     'Touring Front Wheel',  'LL Mountain Rear Wheel',
 ...
             'Rear Brakes',        'Front Derailleur',
            'Front Brakes',             'LL Crankset',
             'ML Crankset',             'HL Crankset',
       'LL Bottom Bracket',       'ML Bottom Bracket',
       'HL Bottom Bracket',            'Mountain-500']
Length: 119, dtype: str

Subcategory:
<StringArray>
[          'Jerseys',             'Forks',        'Handlebars',
            'Wheels',            'Shorts',             'Locks',
             'Pumps',            'Lights', 'Bottles and Cages',
   'Tires and Tubes',           'Saddles',            'Pedals',
            'Chains',           'Helmets',             'Socks',
              'Caps',          'Headsets',          'Panniers',
            'Tights',        'Bib-Shorts',            'Gloves',
             'Vests',        'Bike Racks',          'Cleaners',
           'Fenders',       'Bike Stands',   'Hydration Packs',
   'Mountain Frames',    'Touring Frames',       'Derailleurs',
        'Road Bikes',    'Mountain Bikes',     'Touring Bikes',
       'Road Frames',            'Brakes',         'Cranksets',
   'Bottom Brackets']
Length: 37, dtype: str

Category:
<StringArray>
['Clothing', 'Components', 'Accessories', 'Bikes']
Length: 4, dtype: str

DimReseller
-----------

BusinessType:
<StringArray>
['Specialty Bike Shop', 'Warehouse', 'Value Added Reseller']
Length: 3, dtype: str

DimSalesTerritory
-----------------

SalesTerritoryRegion:
<StringArray>
[     'Northwest',      'Northeast',        'Central',      'Southwest',
      'Southeast',         'Canada',         'France',        'Germany',
      'Australia', 'United Kingdom']
Length: 10, dtype: str

SalesTerritoryCountry:
<StringArray>
['United States', 'Canada', 'France', 'Germany', 'Australia',
 'United Kingdom']
Length: 6, dtype: str

SalesTerritoryGroup:
<StringArray>
['North America', 'Europe', 'Pacific']
Length: 3, dtype: str

In [23]:

numeric_checks = {
    "DimCustomer": ["YearlyIncome", "HouseOwnerFlag"],
    "DimProduct": ["ProductKey"],
    "DimGeography": ["GeographyKey"],
    "DimReseller": ["ResellerKey"],
    "DimSalesTerritory": ["SalesTerritoryKey"]
}

for name, columns in numeric_checks.items():
    print(f"\n{name}")
    print("-" * len(name))
    
    for column in columns:
        print(f"\n{column}:")
        print("Min:", datasets[name][column].min())
        print("Max:", datasets[name][column].max())

DimCustomer
-----------

YearlyIncome:
Min: 10000
Max: 170000

HouseOwnerFlag:
Min: 0
Max: 1

DimProduct
----------

ProductKey:
Min: 210
Max: 606

DimGeography
------------

GeographyKey:
Min: 1
Max: 655

DimReseller
-----------

ResellerKey:
Min: 1
Max: 701

DimSalesTerritory
-----------------

SalesTerritoryKey:
Min: 1
Max: 11

In [24]:

date_checks = {
    "DimCustomer": ["BirthDate", "FirstPurchaseDate"],
    "FactInternetSales": ["OrderDate", "DueDate", "ShipDate"],
    "FactResellerSales": ["OrderDate", "DueDate", "ShipDate"]
}

for name, columns in date_checks.items():
    print(f"\n{name}")
    print("-" * len(name))

    df = datasets[name]

    for column in columns:
        dates = pd.to_datetime(df[column], errors="coerce")
        print(f"{column}: {dates.min()} → {dates.max()}")

DimCustomer
-----------
BirthDate: 1916-02-10 00:00:00 → 1986-06-25 00:00:00
FirstPurchaseDate: 2010-12-29 00:00:00 → 2014-01-28 00:00:00

FactInternetSales
-----------------
OrderDate: 2010-12-29 00:00:00 → 2014-01-28 00:00:00
DueDate: 2011-01-10 00:00:00 → 2014-02-09 00:00:00
ShipDate: 2011-01-05 00:00:00 → 2014-02-04 00:00:00

FactResellerSales
-----------------
OrderDate: 2010-12-29 00:00:00 → 2013-11-29 00:00:00
DueDate: 2011-01-10 00:00:00 → 2013-12-11 00:00:00
ShipDate: 2011-01-05 00:00:00 → 2013-12-06 00:00:00

In [25]:

print("FactInternetSales columns:")
print(fact_internet.columns.tolist())

print("\nFactResellerSales columns:")
print(fact_reseller.columns.tolist())

FactInternetSales columns:
['ProductKey', 'CustomerKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

FactResellerSales columns:
['ProductKey', 'ResellerKey', 'EmployeeKey', 'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber', 'DiscountAmount', 'TotalProductCost', 'SalesAmount', 'Freight', 'CarrierTrackingNumber', 'OrderDate', 'DueDate', 'ShipDate']

In [27]:

cleaned_datasets = {
    name: df.copy()
    for name, df in datasets.items()
}

In [28]:

for name, df in cleaned_datasets.items():
    cleaned_datasets[name] = df.dropna(how="all").copy()

print("Completely blank rows removed from working datasets.")

Completely blank rows removed from working datasets.

In [29]:

cleaned_datasets["FactResellerSales"] = cleaned_datasets["FactResellerSales"][
    cleaned_datasets["FactResellerSales"]["ProductKey"].notna()
].copy()

print(
    "FactResellerSales rows after removing non-transaction rows:",
    len(cleaned_datasets["FactResellerSales"])
)

FactResellerSales rows after removing non-transaction rows: 60855

In [30]:

cleaned_datasets["DimProduct"]["Color"] = (
    cleaned_datasets["DimProduct"]["Color"].fillna("Unknown")
)

print(
    "Missing Color values after treatment:",
    cleaned_datasets["DimProduct"]["Color"].isna().sum()
)

Missing Color values after treatment: 0

In [31]:

cleaned_datasets["DimEmployee"]["ParentEmployeeKey"] = (
    cleaned_datasets["DimEmployee"]["ParentEmployeeKey"].fillna(0)
)

print(
    "Missing ParentEmployeeKey values after treatment:",
    cleaned_datasets["DimEmployee"]["ParentEmployeeKey"].isna().sum()
)

Missing ParentEmployeeKey values after treatment: 0

In [32]:

date_columns = ["OrderDate", "DueDate", "ShipDate"]

for name in ["FactInternetSales", "FactResellerSales"]:
    for column in date_columns:
        cleaned_datasets[name][column] = pd.to_datetime(
            cleaned_datasets[name][column],
            errors="coerce"
        )

print("Fact table date columns converted to datetime format.")

Fact table date columns converted to datetime format.

In [33]:

for name, df in cleaned_datasets.items():
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print(f"\n{name}")
    print("-" * len(name))

    if missing.empty:
        print("No missing values")
    else:
        print(missing)

DimCustomer
-----------
No missing values

DimEmployee
-----------
No missing values

DimGeography
------------
No missing values

DimProduct
----------
No missing values

DimReseller
-----------
No missing values

DimSalesTerritory
-----------------
SalesTerritoryRegion     1
SalesTerritoryCountry    1
SalesTerritoryGroup      1
dtype: int64

FactInternetSales
-----------------
CarrierTrackingNumber    60398
dtype: int64

FactResellerSales
-----------------
No missing values

In [34]:

cleaned_datasets["DimSalesTerritory"][
    cleaned_datasets["DimSalesTerritory"]["SalesTerritoryRegion"].isna()
]

,SalesTerritoryKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
10,11,NaN,NaN,NaN

In [35]:

territory_columns = [
    "SalesTerritoryRegion",
    "SalesTerritoryCountry",
    "SalesTerritoryGroup"
]

cleaned_datasets["DimSalesTerritory"][territory_columns] = (
    cleaned_datasets["DimSalesTerritory"][territory_columns].fillna("Unknown")
)

print(
    "Remaining missing values in DimSalesTerritory:",
    cleaned_datasets["DimSalesTerritory"][territory_columns].isna().sum().sum()
)

Remaining missing values in DimSalesTerritory: 0

In [36]:

print("Final Dataset Validation")
print("=" * 30)

for name, df in cleaned_datasets.items():
    print(f"\n{name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Completely blank rows:", df.isna().all(axis=1).sum())

Final Dataset Validation
==============================

DimCustomer
Rows: 18484
Columns: 13
Duplicate rows: 0
Completely blank rows: 0

DimEmployee
Rows: 21
Columns: 9
Duplicate rows: 0
Completely blank rows: 0

DimGeography
Rows: 655
Columns: 6
Duplicate rows: 0
Completely blank rows: 0

DimProduct
Rows: 397
Columns: 7
Duplicate rows: 0
Completely blank rows: 0

DimReseller
Rows: 701
Columns: 4
Duplicate rows: 0
Completely blank rows: 0

DimSalesTerritory
Rows: 11
Columns: 4
Duplicate rows: 0
Completely blank rows: 0

FactInternetSales
Rows: 60398
Columns: 13
Duplicate rows: 0
Completely blank rows: 0

FactResellerSales
Rows: 60855
Columns: 14
Duplicate rows: 0
Completely blank rows: 0

In [37]:

PROCESSED_PATH = "../data/processed"

os.makedirs(PROCESSED_PATH, exist_ok=True)

for name, df in cleaned_datasets.items():
    file_path = os.path.join(PROCESSED_PATH, f"{name}.csv")
    df.to_csv(file_path, index=False)

print("Cleaned datasets saved successfully.")

Cleaned datasets saved successfully.

In [39]:

for name in cleaned_datasets.keys():
    file_path = os.path.join(PROCESSED_PATH, f"{name}.csv")
    
    check_df = pd.read_csv(file_path)
    
    print(f"{name}.csv: {check_df.shape}")

DimCustomer.csv: (18484, 13)
DimEmployee.csv: (21, 9)
DimGeography.csv: (655, 6)
DimProduct.csv: (397, 7)
DimReseller.csv: (701, 4)
DimSalesTerritory.csv: (11, 4)
FactInternetSales.csv: (60398, 13)
FactResellerSales.csv: (60855, 14)